version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/grafana
      # - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      # - echo "Building the Docker image... $REPOSITORY_URI:$IMAGE_TAG"
      - echo "Building the Docker image... $REPOSITORY_URI"
      - docker build -t grafana .
      - docker tag grafana:latest $REPOSITORY_URI:latest
      # - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - sleep 10

  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker images
      - docker push $REPOSITORY_URI:latest
      # - docker push $REPOSITORY_URI:$IMAGE_TAG

# artifacts:
#   files:
#     - imagedefinitions.json # Optional: If using CodePipeline for deployment
