version: '2'
services:
  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
  grafana:
    image: grafana/grafana
    hostname: grafana
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres:5432
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: grafana
