{
 "title": "Streaming",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Possible Fraud",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  --created_at AS \"time\",\n  $__timeGroup(\"created_at\",'10s'),\n  count(id)\nFROM possible_frauds\nWHERE $__timeFilter(created_at)\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Possible Fraud Data",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT id AS \"Id\", name AS \"Name\", credit_card AS \"Credit Card\", total_amount AS \"Total Amount\", transaction_count As \"Transaction Count\", created_at AS \"Created Time\" \nFROM public.possible_frauds\nWHERE $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic=\"dbserver1.public.transactions\"}[5m]))",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic=\"FLATTEN_TRANSACTIONS\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}